/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.2 Component Pack 6
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <SAIDA_VEL_aliases.h>
#include <SAIDA_VEL.h>
#include <LCD.h>
#include <MSG_1.h>
#include <ENT_TORQUE_aliases.h>
#include <ENT_TORQUE.h>
#include <isr_1.h>
#include <Timer.h>
#include <timer_clock.h>
#include <MAD_2.h>
#include <ENT_ALFA_aliases.h>
#include <ENT_ALFA.h>
#include <MAD_1.h>
#include <PINO_PROCESSAMENTO_aliases.h>
#include <PINO_PROCESSAMENTO.h>
#include <LCD_LCDPort_aliases.h>
#include <LCD_LCDPort.h>
#include <MAD_2_IRQ.h>
#include <MAD_2_theACLK.h>
#include <MAD_2_Bypass_aliases.h>
#include <MAD_2_Bypass.h>
#include <MAD_1_IRQ.h>
#include <MAD_1_theACLK.h>
#include <MAD_1_Bypass_aliases.h>
#include <MAD_1_Bypass.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/

